apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: z5dq7vl2i-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: z5dq7vl2i-nodejs 
  name: z5dq7vl2i-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: z5dq7vl2i-nodejs 
